Fix mispelling in MarshallableMarshaller, add ByteBuf as a default marshaller.
elytra/Concrete pull request #1
Opened 2017-01-14 08:16 UTC by darkevilmac

I'm not sure what happened with the formatting, if you want me to fix that before merging I can do that I guess.

2017-01-14 08:33 UTC, exaskye requested changes

2017-01-14 08:33 UTC, unascribed commented on src/main/java/io/github/elytra/concrete/DefaultMarshallers.java
> +		put(BYTEBUF, "bytebuf", "buf");
This will require you to specify "bytebuf" in \@MarshalledAs - you should put it in the checks in getByType instead so it's a default.

2017-01-14 08:33 UTC, unascribed commented on src/main/java/io/github/elytra/concrete/DefaultMarshallers.java
> +				out.writeBytes(t.readBytes(t.readableBytes()));
Isn't there an easier way to do this?

2017-01-14 08:33 UTC, unascribed commented on src/main/java/io/github/elytra/concrete/DefaultMarshallers.java
> +			name = name.substring(0, name.length() - 5);
Formatting "fixes" do not belong in this PR.

2017-01-14 08:33 UTC, unascribed commented on src/main/java/io/github/elytra/concrete/DefaultMarshallers.java
> +import io.netty.buffer.ByteBuf;
Don't reorganize the imports.

2017-01-14 08:39 UTC, darkevilmac commented on src/main/java/io/github/elytra/concrete/DefaultMarshallers.java
> +				out.writeBytes(t.readBytes(t.readableBytes()));
I tried a couple different things, this worked the best. Writing the internal array doesn't always work, and brings a bunch of junk data along with it. If you can think of something I missed then let me know.

2017-01-14 08:39 UTC, darkevilmac commented on src/main/java/io/github/elytra/concrete/DefaultMarshallers.java
> +import io.netty.buffer.ByteBuf;
k

2017-01-14 17:40 UTC, jamierocks commented on src/main/java/io/github/elytra/concrete/DefaultMarshallers.java
> +}
newline

2017-01-14 17:40 UTC, jamierocks commented on src/main/java/io/github/elytra/concrete/DefaultMarshallers.java
> +		} else if (ByteBuf.class.isAssignableFrom(type)){
space before `{`

2017-01-14 17:40 UTC, jamierocks commented on src/main/java/io/github/elytra/concrete/DefaultMarshallers.java
> +
could you revert these?

2017-01-15 04:05 UTC, exaskye approved these changes

2017-01-15 14:00 UTC, jamierocks approved these changes
👍

2017-01-28 13:14 UTC, merged